import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Main from '../components/Main'
import Card from '../components/Card'

const HomePage = ({ posts }) => {
  return (
    <div className="flex-layout">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <div className="container">
        </div>
        <div className="container container-wrapper">
          <ul>
            <Card posts={posts} />
          </ul>
        </div>
      </Main>
      <Footer />
    </div>
  )
} 

HomePage.getInitialProps = async function (ctx) {
  const p_res = await fetch('http://localhost:5035/api/posts')
  const posts = await p_res.json()

  return {
    posts: posts.data
  }
}

export default HomePage