import Head from 'next/head'
import Footer from '../../components/Footer'
import Header from '../../components/Header'
import Main from '../../components/Main'
import Tag from '../../components/Tag'

const Home = ({ tags }) => {
  return (
    <div className="flex-layout">
      <Head>
        <title>#tags</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <div className="container">
            <Tag tags={tags} />
        </div>
      </Main>
      <Footer />
    </div>
  )
} 

Home.getInitialProps = async function (ctx) {
  const t_res = await fetch('http://localhost:5035/api/tags')
  const tags = await t_res.json()

  return {
    tags: tags.data
  }
}

export default Home